name: Continuous

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      # - name: Install Cypress
      #   run: npm run cy:install

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          # wait-on: 'http://localhost:3333'
          # install: false
          # browser: chrome
          # env: type=actual
          spec: |
            cypress/e2e/base/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Visual:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'npm'
  #         cache-dependency-path: '**/package-lock.json'

  #     - name: Update NPM registry
  #       run: npm run registry

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Install Cypress
  #       run: npm run cy:install

  #     - name: Run Cypress
  #       uses: cypress-io/github-action@v4
  #       with:
  #         build: npm run cy:build
  #         start: npm run cy:start
  #         wait-on: 'http://localhost:3333'
  #         install: false
  #         browser: chrome
  #         env: type=actual
  #         spec: |
  #           cypress/e2e/visual/*.cy.ts
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload snapshots
  #       uses: actions/upload-artifact@v3
  #       if: failure()
  #       with:
  #         name: cypress-snapshots
  #         path: cypress/snapshots
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Upload videos
  #       uses: actions/upload-artifact@v3
  #       if: failure()
  #       with:
  #         name: cypress-videos
  #         path: cypress/videos
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
